
# Use an official Python runtime as a parent image
FROM centos:centos6.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD ClinSV_x86_64_v0.9.tar.gz /app
ADD ClinSV_scripts_only_v0.9.tar.gz /app

# install root
RUN yum -y install epel-release 
RUN yum -y install gcc-c++ bzip2 git vim libpng libjpeg      python-devel libSM libX11 libXext libXpm libXft gsl-devel python-pip make cmake3     && yum -y clean all
#RUN pip install --upgrade pip && pip install jupyter
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

# Set ROOT environment
ENV ROOTSYS         "/app/clinsv/root"
ENV PATH            "$ROOTSYS/bin:/bin/bin:$PATH"
ENV LD_LIBRARY_PATH "$ROOTSYS/lib:$LD_LIBRARY_PATH"
ENV PYTHONPATH      "$ROOTSYS/lib:$PYTHONPATH"

# Install any needed packages specified in requirements.txt
RUN yum install -y libpng-devel
RUN yum install -y mysql-libs-5.1.73-8.el6_8.x86_64

# for QC reprot
RUN yum install -y libgfortran
RUN yum install -y texlive-latex-2007-60.el6_7.x86_64

# Define environment variable
ENV PATH="/app/clinsv/bin:${PATH}"

# Run app.py when the container launches
ENTRYPOINT ["/app/clinsv/bin/perl","/app/clinsv/bin/clinsv"]


